# Generated by Django 5.0.9 on 2026-03-28 20:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('time_of_birth', models.TimeField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('birth_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('birth_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_city', models.CharField(blank=True, default='', max_length=100)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('sexual_orientation', models.CharField(choices=[('straight', 'Straight'), ('lesbian', 'Lesbian'), ('gay', 'Gay'), ('bisexual', 'Bisexual'), ('pansexual', 'Pansexual'), ('other', 'Other')], max_length=20)),
                ('dating_preference', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('everyone', 'Everyone')], max_length=20)),
                ('religion', models.CharField(blank=True, choices=[('hindu', 'Hindu'), ('muslim', 'Muslim'), ('sikh', 'Sikh'), ('christian', 'Christian'), ('jain', 'Jain'), ('buddhist', 'Buddhist'), ('other', 'Other')], default='', max_length=20)),
                ('caste', models.CharField(blank=True, default='', max_length=100)),
                ('mother_tongue', models.CharField(blank=True, default='', max_length=100)),
                ('marital_status', models.CharField(blank=True, choices=[('never_married', 'Never Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='', max_length=20)),
                ('min_age_preference', models.PositiveIntegerField(default=22)),
                ('max_age_preference', models.PositiveIntegerField(default=35)),
                ('max_distance_km', models.PositiveIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profiles',
                'indexes': [models.Index(fields=['current_city'], name='profiles_current_00555a_idx'), models.Index(fields=['dating_preference'], name='profiles_dating__589e9f_idx'), models.Index(fields=['religion'], name='profiles_religio_c703a6_idx'), models.Index(fields=['marital_status'], name='profiles_marital_2efd6d_idx'), models.Index(fields=['current_lat', 'current_lng'], name='profiles_current_e7acfe_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_key', models.CharField(max_length=512)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='profiles.profile')),
            ],
            options={
                'db_table': 'profile_images',
                'ordering': ['order'],
            },
        ),
    ]
