# Generated by Django 5.0.9 on 2026-03-28 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthChart',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='birth_chart', serialize=False, to='profiles.profile')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('rashi', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rashi_name', models.CharField(blank=True, default='', max_length=50)),
                ('lagna', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lagna_name', models.CharField(blank=True, default='', max_length=50)),
                ('nakshatra', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nakshatra_name', models.CharField(blank=True, default='', max_length=50)),
                ('nakshatra_pada', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gana', models.CharField(blank=True, choices=[('deva', 'Deva'), ('manushya', 'Manushya'), ('rakshasa', 'Rakshasa')], default='', max_length=20)),
                ('yoni', models.CharField(blank=True, default='', max_length=50)),
                ('varna', models.CharField(blank=True, default='', max_length=50)),
                ('nadi', models.CharField(blank=True, default='', max_length=20)),
                ('bhakoot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_manglik', models.BooleanField(null=True)),
                ('manglik_intensity', models.CharField(blank=True, default='none', max_length=20)),
                ('planetary_positions', models.JSONField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'birth_charts',
                'indexes': [models.Index(fields=['status'], name='birth_chart_status_ba09cb_idx'), models.Index(fields=['rashi'], name='birth_chart_rashi_07ad5e_idx'), models.Index(fields=['nakshatra'], name='birth_chart_nakshat_1d7dbe_idx')],
            },
        ),
    ]
