# Generated by Django 5.0.9 on 2026-03-28 20:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('varna_score', models.PositiveSmallIntegerField(default=0)),
                ('vasya_score', models.PositiveSmallIntegerField(default=0)),
                ('tara_score', models.PositiveSmallIntegerField(default=0)),
                ('yoni_score', models.PositiveSmallIntegerField(default=0)),
                ('graha_maitri_score', models.PositiveSmallIntegerField(default=0)),
                ('gana_score', models.PositiveSmallIntegerField(default=0)),
                ('bhakoot_score', models.PositiveSmallIntegerField(default=0)),
                ('nadi_score', models.PositiveSmallIntegerField(default=0)),
                ('guna_milan_total', models.PositiveSmallIntegerField(default=0)),
                ('is_manglik_compatible', models.BooleanField(default=True)),
                ('overall_score', models.FloatField(default=0.0)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('narrative_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compatibility_scores',
            },
        ),
        migrations.CreateModel(
            name='UserMatchDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_match_decisions',
            },
        ),
    ]
