# Generated by Django 5.0.9 on 2026-03-28 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibilityscore',
            name='user_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_as_a', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='compatibilityscore',
            name='user_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_as_b', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='usermatchdecision',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_received', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='usermatchdecision',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_made', to='profiles.profile'),
        ),
        migrations.AddIndex(
            model_name='compatibilityscore',
            index=models.Index(fields=['user_a', '-overall_score'], name='compatibili_user_a__67aa42_idx'),
        ),
        migrations.AddIndex(
            model_name='compatibilityscore',
            index=models.Index(fields=['user_b', '-overall_score'], name='compatibili_user_b__110fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='compatibilityscore',
            index=models.Index(fields=['guna_milan_total'], name='compatibili_guna_mi_b27554_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compatibilityscore',
            unique_together={('user_a', 'user_b')},
        ),
        migrations.AddIndex(
            model_name='usermatchdecision',
            index=models.Index(fields=['user', 'decision'], name='user_match__user_id_4968e1_idx'),
        ),
        migrations.AddIndex(
            model_name='usermatchdecision',
            index=models.Index(fields=['candidate', 'decision'], name='user_match__candida_6e5a9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermatchdecision',
            unique_together={('user', 'candidate')},
        ),
    ]
