// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgsldvqrgkxxdpuxtbna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnc2xkdnFyZ2t4eGRwdXh0Ym5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTIyODQsImV4cCI6MjA2NTQ4ODI4NH0.TegPV8tBBD4v34yUCgtT8u7GtYtYLXCj8Pv-UXk8f6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);